name: vams

services:
  mysql:
    image: mysql:latest
    restart: always
    ports: 
      - "${DB_PORT-3306}:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks: 
      - vams
    volumes:
      - mysql:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  keycloak:
    build:
      context: .
      dockerfile: ./keycloak.dev.Dockerfile
    depends_on:
      - mysql
    restart: always
    networks: 
      - vams
    environment:
      - KC_DB=${KC_DB}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${DB_USERNAME}
      - KC_DB_PASSWORD=${DB_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    ports: 
      - 8082:8080
    command: start-dev

volumes: 
  mysql:

networks:
  vams: 
